# coding: utf-8

"""
    phishingapi

    Easily and directly scan and block phishing security threats in input.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_phishing_api_client
from cloudmersive_phishing_api_client.models.advanced_url_detection_request import AdvancedUrlDetectionRequest  # noqa: E501
from cloudmersive_phishing_api_client.rest import ApiException


class TestAdvancedUrlDetectionRequest(unittest.TestCase):
    """AdvancedUrlDetectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdvancedUrlDetectionRequest(self):
        """Test AdvancedUrlDetectionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_phishing_api_client.models.advanced_url_detection_request.AdvancedUrlDetectionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
