# coding: utf-8

"""
    phishingapi

    Easily and directly scan and block phishing security threats in input.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_phishing_api_client
from cloudmersive_phishing_api_client.models.prior_history_item import PriorHistoryItem  # noqa: E501
from cloudmersive_phishing_api_client.rest import ApiException


class TestPriorHistoryItem(unittest.TestCase):
    """PriorHistoryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriorHistoryItem(self):
        """Test PriorHistoryItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_phishing_api_client.models.prior_history_item.PriorHistoryItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
