# coding: utf-8

"""
    phishingapi

    Easily and directly scan and block phishing security threats in input.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AdvancedUrlDetectionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'custom_policy_id': 'str'
    }

    attribute_map = {
        'url': 'Url',
        'custom_policy_id': 'CustomPolicyID'
    }

    def __init__(self, url=None, custom_policy_id=None):  # noqa: E501
        """AdvancedUrlDetectionRequest - a model defined in Swagger"""  # noqa: E501

        self._url = None
        self._custom_policy_id = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if custom_policy_id is not None:
            self.custom_policy_id = custom_policy_id

    @property
    def url(self):
        """Gets the url of this AdvancedUrlDetectionRequest.  # noqa: E501

        URL to check for phishing  # noqa: E501

        :return: The url of this AdvancedUrlDetectionRequest.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AdvancedUrlDetectionRequest.

        URL to check for phishing  # noqa: E501

        :param url: The url of this AdvancedUrlDetectionRequest.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def custom_policy_id(self):
        """Gets the custom_policy_id of this AdvancedUrlDetectionRequest.  # noqa: E501

        Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud  # noqa: E501

        :return: The custom_policy_id of this AdvancedUrlDetectionRequest.  # noqa: E501
        :rtype: str
        """
        return self._custom_policy_id

    @custom_policy_id.setter
    def custom_policy_id(self, custom_policy_id):
        """Sets the custom_policy_id of this AdvancedUrlDetectionRequest.

        Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud  # noqa: E501

        :param custom_policy_id: The custom_policy_id of this AdvancedUrlDetectionRequest.  # noqa: E501
        :type: str
        """

        self._custom_policy_id = custom_policy_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdvancedUrlDetectionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdvancedUrlDetectionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
