# coding: utf-8

"""
    phishingapi

    Easily and directly scan and block phishing security threats in input.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PhishingDetectionTextStringRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_string': 'str',
        'model': 'str',
        'provide_analysis_rationale': 'bool'
    }

    attribute_map = {
        'input_string': 'InputString',
        'model': 'Model',
        'provide_analysis_rationale': 'ProvideAnalysisRationale'
    }

    def __init__(self, input_string=None, model=None, provide_analysis_rationale=None):  # noqa: E501
        """PhishingDetectionTextStringRequest - a model defined in Swagger"""  # noqa: E501

        self._input_string = None
        self._model = None
        self._provide_analysis_rationale = None
        self.discriminator = None

        if input_string is not None:
            self.input_string = input_string
        if model is not None:
            self.model = model
        if provide_analysis_rationale is not None:
            self.provide_analysis_rationale = provide_analysis_rationale

    @property
    def input_string(self):
        """Gets the input_string of this PhishingDetectionTextStringRequest.  # noqa: E501

        Input text string to detect phishing against  # noqa: E501

        :return: The input_string of this PhishingDetectionTextStringRequest.  # noqa: E501
        :rtype: str
        """
        return self._input_string

    @input_string.setter
    def input_string(self, input_string):
        """Sets the input_string of this PhishingDetectionTextStringRequest.

        Input text string to detect phishing against  # noqa: E501

        :param input_string: The input_string of this PhishingDetectionTextStringRequest.  # noqa: E501
        :type: str
        """

        self._input_string = input_string

    @property
    def model(self):
        """Gets the model of this PhishingDetectionTextStringRequest.  # noqa: E501

        Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.  # noqa: E501

        :return: The model of this PhishingDetectionTextStringRequest.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this PhishingDetectionTextStringRequest.

        Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.  # noqa: E501

        :param model: The model of this PhishingDetectionTextStringRequest.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def provide_analysis_rationale(self):
        """Gets the provide_analysis_rationale of this PhishingDetectionTextStringRequest.  # noqa: E501

        Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.  # noqa: E501

        :return: The provide_analysis_rationale of this PhishingDetectionTextStringRequest.  # noqa: E501
        :rtype: bool
        """
        return self._provide_analysis_rationale

    @provide_analysis_rationale.setter
    def provide_analysis_rationale(self, provide_analysis_rationale):
        """Sets the provide_analysis_rationale of this PhishingDetectionTextStringRequest.

        Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.  # noqa: E501

        :param provide_analysis_rationale: The provide_analysis_rationale of this PhishingDetectionTextStringRequest.  # noqa: E501
        :type: bool
        """

        self._provide_analysis_rationale = provide_analysis_rationale

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhishingDetectionTextStringRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhishingDetectionTextStringRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
