# coding: utf-8

"""
    phishingapi

    Easily and directly scan and block phishing security threats in input.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PhishingDetectionAdvancedRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_string': 'str',
        'text_type': 'str',
        'model': 'str',
        'allow_unsolicited_sales': 'bool',
        'allow_promotional_content': 'bool',
        'allow_web_urls': 'bool',
        'allow_phone_numbers': 'bool',
        'allow_email_addresses': 'bool',
        'provide_url_analysis': 'bool',
        'custom_policy_id': 'str',
        'provide_analysis_rationale': 'bool',
        'from_name': 'str',
        'to_name': 'str',
        'from_phone_number': 'str',
        'to_phone_number': 'str',
        'from_email_address': 'str',
        'to_email_address': 'str'
    }

    attribute_map = {
        'input_string': 'InputString',
        'text_type': 'TextType',
        'model': 'Model',
        'allow_unsolicited_sales': 'AllowUnsolicitedSales',
        'allow_promotional_content': 'AllowPromotionalContent',
        'allow_web_urls': 'AllowWebUrls',
        'allow_phone_numbers': 'AllowPhoneNumbers',
        'allow_email_addresses': 'AllowEmailAddresses',
        'provide_url_analysis': 'ProvideUrlAnalysis',
        'custom_policy_id': 'CustomPolicyID',
        'provide_analysis_rationale': 'ProvideAnalysisRationale',
        'from_name': 'FromName',
        'to_name': 'ToName',
        'from_phone_number': 'FromPhoneNumber',
        'to_phone_number': 'ToPhoneNumber',
        'from_email_address': 'FromEmailAddress',
        'to_email_address': 'ToEmailAddress'
    }

    def __init__(self, input_string=None, text_type=None, model=None, allow_unsolicited_sales=None, allow_promotional_content=None, allow_web_urls=None, allow_phone_numbers=None, allow_email_addresses=None, provide_url_analysis=None, custom_policy_id=None, provide_analysis_rationale=None, from_name=None, to_name=None, from_phone_number=None, to_phone_number=None, from_email_address=None, to_email_address=None):  # noqa: E501
        """PhishingDetectionAdvancedRequest - a model defined in Swagger"""  # noqa: E501

        self._input_string = None
        self._text_type = None
        self._model = None
        self._allow_unsolicited_sales = None
        self._allow_promotional_content = None
        self._allow_web_urls = None
        self._allow_phone_numbers = None
        self._allow_email_addresses = None
        self._provide_url_analysis = None
        self._custom_policy_id = None
        self._provide_analysis_rationale = None
        self._from_name = None
        self._to_name = None
        self._from_phone_number = None
        self._to_phone_number = None
        self._from_email_address = None
        self._to_email_address = None
        self.discriminator = None

        if input_string is not None:
            self.input_string = input_string
        if text_type is not None:
            self.text_type = text_type
        if model is not None:
            self.model = model
        if allow_unsolicited_sales is not None:
            self.allow_unsolicited_sales = allow_unsolicited_sales
        if allow_promotional_content is not None:
            self.allow_promotional_content = allow_promotional_content
        if allow_web_urls is not None:
            self.allow_web_urls = allow_web_urls
        if allow_phone_numbers is not None:
            self.allow_phone_numbers = allow_phone_numbers
        if allow_email_addresses is not None:
            self.allow_email_addresses = allow_email_addresses
        if provide_url_analysis is not None:
            self.provide_url_analysis = provide_url_analysis
        if custom_policy_id is not None:
            self.custom_policy_id = custom_policy_id
        if provide_analysis_rationale is not None:
            self.provide_analysis_rationale = provide_analysis_rationale
        if from_name is not None:
            self.from_name = from_name
        if to_name is not None:
            self.to_name = to_name
        if from_phone_number is not None:
            self.from_phone_number = from_phone_number
        if to_phone_number is not None:
            self.to_phone_number = to_phone_number
        if from_email_address is not None:
            self.from_email_address = from_email_address
        if to_email_address is not None:
            self.to_email_address = to_email_address

    @property
    def input_string(self):
        """Gets the input_string of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Input text string to detect phishing against  # noqa: E501

        :return: The input_string of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._input_string

    @input_string.setter
    def input_string(self, input_string):
        """Sets the input_string of this PhishingDetectionAdvancedRequest.

        Input text string to detect phishing against  # noqa: E501

        :param input_string: The input_string of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._input_string = input_string

    @property
    def text_type(self):
        """Gets the text_type of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Type of text being analyzed. Must be one of: \"TextMessage\", \"UserMessage\", \"SalesLead\", \"EmailMessage\", \"SupportCase\", \"AppMessage\", \"Other\".  # noqa: E501

        :return: The text_type of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._text_type

    @text_type.setter
    def text_type(self, text_type):
        """Sets the text_type of this PhishingDetectionAdvancedRequest.

        Optional: Type of text being analyzed. Must be one of: \"TextMessage\", \"UserMessage\", \"SalesLead\", \"EmailMessage\", \"SupportCase\", \"AppMessage\", \"Other\".  # noqa: E501

        :param text_type: The text_type of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._text_type = text_type

    @property
    def model(self):
        """Gets the model of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.  # noqa: E501

        :return: The model of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this PhishingDetectionAdvancedRequest.

        Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.  # noqa: E501

        :param model: The model of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def allow_unsolicited_sales(self):
        """Gets the allow_unsolicited_sales of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: True if unsolicited sales should be allowed, false otherwise. Defaults to true.  # noqa: E501

        :return: The allow_unsolicited_sales of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_unsolicited_sales

    @allow_unsolicited_sales.setter
    def allow_unsolicited_sales(self, allow_unsolicited_sales):
        """Sets the allow_unsolicited_sales of this PhishingDetectionAdvancedRequest.

        Optional: True if unsolicited sales should be allowed, false otherwise. Defaults to true.  # noqa: E501

        :param allow_unsolicited_sales: The allow_unsolicited_sales of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: bool
        """

        self._allow_unsolicited_sales = allow_unsolicited_sales

    @property
    def allow_promotional_content(self):
        """Gets the allow_promotional_content of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: True if promotional content should be allowed, false otherwise. Defaults to true.  # noqa: E501

        :return: The allow_promotional_content of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_promotional_content

    @allow_promotional_content.setter
    def allow_promotional_content(self, allow_promotional_content):
        """Sets the allow_promotional_content of this PhishingDetectionAdvancedRequest.

        Optional: True if promotional content should be allowed, false otherwise. Defaults to true.  # noqa: E501

        :param allow_promotional_content: The allow_promotional_content of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: bool
        """

        self._allow_promotional_content = allow_promotional_content

    @property
    def allow_web_urls(self):
        """Gets the allow_web_urls of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: True if web URLs should be allowed in the input text, false otherwise. Defaults to true. When false, input containing URLs (including homoglyph URLs and spaced-out URLs) will be flagged as not clean.  # noqa: E501

        :return: The allow_web_urls of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_web_urls

    @allow_web_urls.setter
    def allow_web_urls(self, allow_web_urls):
        """Sets the allow_web_urls of this PhishingDetectionAdvancedRequest.

        Optional: True if web URLs should be allowed in the input text, false otherwise. Defaults to true. When false, input containing URLs (including homoglyph URLs and spaced-out URLs) will be flagged as not clean.  # noqa: E501

        :param allow_web_urls: The allow_web_urls of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: bool
        """

        self._allow_web_urls = allow_web_urls

    @property
    def allow_phone_numbers(self):
        """Gets the allow_phone_numbers of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: True if phone numbers should be allowed in the input text, false otherwise. Defaults to true. When false, input containing phone numbers (including homoglyph digits and spaced-out or spelled-out workarounds) will be flagged as not clean.  # noqa: E501

        :return: The allow_phone_numbers of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_phone_numbers

    @allow_phone_numbers.setter
    def allow_phone_numbers(self, allow_phone_numbers):
        """Sets the allow_phone_numbers of this PhishingDetectionAdvancedRequest.

        Optional: True if phone numbers should be allowed in the input text, false otherwise. Defaults to true. When false, input containing phone numbers (including homoglyph digits and spaced-out or spelled-out workarounds) will be flagged as not clean.  # noqa: E501

        :param allow_phone_numbers: The allow_phone_numbers of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: bool
        """

        self._allow_phone_numbers = allow_phone_numbers

    @property
    def allow_email_addresses(self):
        """Gets the allow_email_addresses of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: True if email addresses should be allowed in the input text, false otherwise. Defaults to true. When false, input containing email addresses (including homoglyph characters and obfuscated workarounds like \"danny at somedomaine [DOT] com\") will be flagged as not clean.  # noqa: E501

        :return: The allow_email_addresses of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_email_addresses

    @allow_email_addresses.setter
    def allow_email_addresses(self, allow_email_addresses):
        """Sets the allow_email_addresses of this PhishingDetectionAdvancedRequest.

        Optional: True if email addresses should be allowed in the input text, false otherwise. Defaults to true. When false, input containing email addresses (including homoglyph characters and obfuscated workarounds like \"danny at somedomaine [DOT] com\") will be flagged as not clean.  # noqa: E501

        :param allow_email_addresses: The allow_email_addresses of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: bool
        """

        self._allow_email_addresses = allow_email_addresses

    @property
    def provide_url_analysis(self):
        """Gets the provide_url_analysis of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: True to perform deep URL analysis on any URLs detected in the text. When enabled, if the initial AI scan detects URLs, a second AI call enumerates them and each URL is individually analyzed for phishing. Defaults to true.  # noqa: E501

        :return: The provide_url_analysis of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._provide_url_analysis

    @provide_url_analysis.setter
    def provide_url_analysis(self, provide_url_analysis):
        """Sets the provide_url_analysis of this PhishingDetectionAdvancedRequest.

        Optional: True to perform deep URL analysis on any URLs detected in the text. When enabled, if the initial AI scan detects URLs, a second AI call enumerates them and each URL is individually analyzed for phishing. Defaults to true.  # noqa: E501

        :param provide_url_analysis: The provide_url_analysis of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: bool
        """

        self._provide_url_analysis = provide_url_analysis

    @property
    def custom_policy_id(self):
        """Gets the custom_policy_id of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud  # noqa: E501

        :return: The custom_policy_id of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._custom_policy_id

    @custom_policy_id.setter
    def custom_policy_id(self, custom_policy_id):
        """Sets the custom_policy_id of this PhishingDetectionAdvancedRequest.

        Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud  # noqa: E501

        :param custom_policy_id: The custom_policy_id of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._custom_policy_id = custom_policy_id

    @property
    def provide_analysis_rationale(self):
        """Gets the provide_analysis_rationale of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.  # noqa: E501

        :return: The provide_analysis_rationale of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: bool
        """
        return self._provide_analysis_rationale

    @provide_analysis_rationale.setter
    def provide_analysis_rationale(self, provide_analysis_rationale):
        """Sets the provide_analysis_rationale of this PhishingDetectionAdvancedRequest.

        Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.  # noqa: E501

        :param provide_analysis_rationale: The provide_analysis_rationale of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: bool
        """

        self._provide_analysis_rationale = provide_analysis_rationale

    @property
    def from_name(self):
        """Gets the from_name of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Name of the sender  # noqa: E501

        :return: The from_name of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._from_name

    @from_name.setter
    def from_name(self, from_name):
        """Sets the from_name of this PhishingDetectionAdvancedRequest.

        Optional: Name of the sender  # noqa: E501

        :param from_name: The from_name of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._from_name = from_name

    @property
    def to_name(self):
        """Gets the to_name of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Name of the recipient  # noqa: E501

        :return: The to_name of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._to_name

    @to_name.setter
    def to_name(self, to_name):
        """Sets the to_name of this PhishingDetectionAdvancedRequest.

        Optional: Name of the recipient  # noqa: E501

        :param to_name: The to_name of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._to_name = to_name

    @property
    def from_phone_number(self):
        """Gets the from_phone_number of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Phone number of the sender  # noqa: E501

        :return: The from_phone_number of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._from_phone_number

    @from_phone_number.setter
    def from_phone_number(self, from_phone_number):
        """Sets the from_phone_number of this PhishingDetectionAdvancedRequest.

        Optional: Phone number of the sender  # noqa: E501

        :param from_phone_number: The from_phone_number of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._from_phone_number = from_phone_number

    @property
    def to_phone_number(self):
        """Gets the to_phone_number of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Phone number of the recipient  # noqa: E501

        :return: The to_phone_number of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._to_phone_number

    @to_phone_number.setter
    def to_phone_number(self, to_phone_number):
        """Sets the to_phone_number of this PhishingDetectionAdvancedRequest.

        Optional: Phone number of the recipient  # noqa: E501

        :param to_phone_number: The to_phone_number of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._to_phone_number = to_phone_number

    @property
    def from_email_address(self):
        """Gets the from_email_address of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Email address of the sender  # noqa: E501

        :return: The from_email_address of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._from_email_address

    @from_email_address.setter
    def from_email_address(self, from_email_address):
        """Sets the from_email_address of this PhishingDetectionAdvancedRequest.

        Optional: Email address of the sender  # noqa: E501

        :param from_email_address: The from_email_address of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._from_email_address = from_email_address

    @property
    def to_email_address(self):
        """Gets the to_email_address of this PhishingDetectionAdvancedRequest.  # noqa: E501

        Optional: Email address of the recipient  # noqa: E501

        :return: The to_email_address of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :rtype: str
        """
        return self._to_email_address

    @to_email_address.setter
    def to_email_address(self, to_email_address):
        """Sets the to_email_address of this PhishingDetectionAdvancedRequest.

        Optional: Email address of the recipient  # noqa: E501

        :param to_email_address: The to_email_address of this PhishingDetectionAdvancedRequest.  # noqa: E501
        :type: str
        """

        self._to_email_address = to_email_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhishingDetectionAdvancedRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhishingDetectionAdvancedRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
